# Generated by Django 3.1.3 on 2023-08-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_comment_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modefy_date',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modefy_date',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modefy_date',
            new_name='modify_date',
        ),
    ]
